version: '3.1'
services:
  app:
    build: .
    image: kurimegane/env-node:latest
    container_name: env-node
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./app:/app
    tty: true
    ports:
      - 4000:4000