version: '3.1'
services:
  app:
    build: env-src
    image: kurimegane/env-node:latest
    container_name: env-node
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./app:/app